name: Auto Feed (VI/EN • One-Paste 24/7)

on:
  schedule:
    - cron: "0 */6 * * *"   # mỗi 6 giờ (00,06,12,18 UTC). Đổi thành "0 0 * * *" nếu muốn mỗi ngày.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate VI & EN feed (AI-lite, no secrets)
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const now = new Date().toISOString();

          const BINANCE = "https://www.binance.com/referral/earn-together/refer-in-hotsummer/claim?hl=vi&ref=GRO_20338_9V44N";
          const ALGOS   = "https://algosone.page.link/MbtR";

          const slotsVI = [
            ["Sáng","Layer2","Theo dõi cầu nối & volume tăng để bắt nhịp sớm."],
            ["Trưa","Funding/Long-Short","Quan sát funding & độ lệch để tối ưu vị thế."],
            ["Tối","Dòng tiền Stablecoin","Dòng vốn vào/ra CEX/DEX cho tín hiệu động lượng."]
          ];
          const slotsEN = [
            ["Morning","Layer2","Bridge flow & rising volume help early entries."],
            ["Midday","Funding/Long-Short","Use funding skew to optimize position sizing."],
            ["Evening","Stablecoin Flows","CEX/DEX netflow signals momentum."]
          ];

          const offers = {
            vi: [
              ["Mở Binance nhận thưởng", BINANCE, ["onboarding","cex"]],
              ["AlgosOne – Chiến lược AI", ALGOS, ["ai","signals"]]
            ],
            en: [
              ["Open Binance for rewards", BINANCE, ["onboarding","cex"]],
              ["AlgosOne – AI strategies", ALGOS, ["ai","signals"]]
            ]
          };

          function pick(a){ return a[Math.floor(Math.random()*a.length)] }
          function idFrom(s){ return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,60)+'-'+Date.now() }

          function make(lang, slots){
            const off = offers[lang];
            const items = slots.map(([dp, topic, note])=>{
              const [ttl, url, tags] = pick(off);
              const title = `${dp} • ${topic} • ${ttl}`;
              return { id:idFrom(title), title, body_html:`<p>${note}</p>`, cta:{label:ttl, url}, tags:[topic.toLowerCase(), ...tags], lang };
            });
            return { updated_at: now, items };
          }

          fs.writeFileSync('feed.vi.json', JSON.stringify(make('vi', slotsVI), null, 2));
          fs.writeFileSync('feed.en.json', JSON.stringify(make('en', slotsEN), null, 2));
          console.log('WROTE feed.vi.json & feed.en.json at', now);
          NODE

      - name: Commit & push feed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add feed.vi.json feed.en.json
            git commit -m "chore(feed): auto-update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
